### ISSUE TITLE
Speed up `draw_xgi_nodes` and `draw_xgi_hyperedges`

### ISSUE THREAD

**Issue by nwlandry** [xgi-org/xgi#174]
If we remove the for-loop in the function that draws the hypergraph nodes with `scatter` and instead pass iterables into the scatter function, it could be faster. Also, if we plot Collection objects instead of Patch objects, maybe it will be faster as well. (https://stackoverflow.com/questions/37573314/matplotlib-efficient-way-to-create-large-number-of-patch-objects)

**Comment by nwlandry** [comment]
This might also be relevant: https://stackoverflow.com/questions/43216111/anyway-to-draw-many-lines-fast-in-python-matploblib-is-preferred-if-possible

**Comment by maximelucas** [comment]
Node speed-up implemented in #211

**Comment by leotrs** [comment]
Any ideas on how to optimize the edge function?

**Comment by nwlandry** [comment]
I tried to make it faster but my recollection was that plotting a collection of patches gave you less control over the color and other properties of individual edges compared with plotting a patch at a time.
