### ISSUE TITLE
Implement method to find free pairs and perform elementary collapses and edge contractions in SCs

### ISSUE THREAD

**Issue by leotrs** [xgi-org/xgi#177]
See e.g. [here](https://hal.inria.fr/hal-00707901v1/document), page 8.

@alpatania do other TDA libraries implement such methods? I ask mostly out of curiosity but also because if such operations (collapses and contractions) are ONLY valuable in the context of TDA, and TDA libraries already implement them, then we might not need to implement them ourselves.

**Comment by maximelucas** [comment]
@alpatania @lordgrilo do we want this? Otherwise we could close.

**Comment by leotrs** [comment]
Closing for now until the need for this feature arises.
