### ISSUE TITLE
Add lattice layouts for plotting

### ISSUE THREAD

**Issue by maximelucas** [xgi-org/xgi#179]
Add an easy way to plot grid, triangular, and other regular lattices with a natural layout.

**Comment by maximelucas** [comment]
I think the way to do this is rather to have generators of lattice models that also output the positions of the nodes. Those positions can then be passed to any drawing function. I would close this an open another issue to suggest implementing lattice generators.

**Comment by leotrs** [comment]
You mean to attach the coordinates to each node as a node attribute?

**Comment by maximelucas** [comment]
Exactly. For example networkx has a `with_positions` argument:
`nx.triangular_lattice_graph(m, n, with_positions=True)`
https://networkx.org/documentation/stable/reference/generated/networkx.generators.lattice.triangular_lattice_graph.html

**Comment by leotrs** [comment]
And once the lattice is generated, there's a special plotting function that looks at the node attributes?

**Comment by maximelucas** [comment]
Networkx does not have one, as far as I know. So you need to manually collect all the positions, and pass them with the `pos` argument. But I agree we could have "lattice draw" functions that do that automatically, or a helper function that collects the positions from node attribute in a format that fits the `pos` argument.

**Comment by leotrs** [comment]
Alternatively, we could have a `pos` argument that works much like `edge_fc` et al in `draw_xgi_simplices`, that is, it could take a dict, a NodeStat, etc. This could be useful for plotting in general, not only for lattice networks.

**Comment by maximelucas** [comment]
We have a [recipe](https://xgi.readthedocs.io/en/latest/api/tutorials/recipes.html#14.-Flag-a-triangular-lattice) doing this for triangular lattices now.

**Comment by nwlandry** [comment]
Closed as per the team meeting today.
