### ISSUE TITLE
add max_order to xgi.draw()

### ISSUE THREAD

**Issue by maximelucas** [xgi-org/xgi#186]
For efficiency when not needing to see large groups.

**Comment by leotrs** [comment]
I wonder if this is overlapping with #182

**Comment by maximelucas** [comment]
In some cases #182 will remove the need for this one, I agree, but not in general in my mind. 
You might need to work and compute measures including large orders (from a dataset or generative model) but be okay not visualising them all the time. 

Actually in the past I had a function to visualise only one size of groups at a time (say triangles). That would be an extension of the present issue.

**Comment by leotrs** [comment]
Agreed! I think we need to implement both so that we can have `xgi.draw(H, max_order=d)` and `xgi.draw` would call `H.cutoff_edges(max_order=d)` at some point (or whatever other method gets rid of the higher order edges).

**Comment by leotrs** [comment]
This is to say I'd implement #182 first before implementing this one.
