### ISSUE TITLE
add edge_size_histogram() function

### ISSUE THREAD

**Issue by maximelucas** [xgi-org/xgi#187]
Right now `xgi.unique_edge_sizes(H)` returns the existing the unique edge sizes in the hypergraph, but does not count them. 

It would be nice to have an easy way to compute a histogram of edge sizes: how many edges have each given size. 

@leotrs mentioned we can use something like 
```python
H.edges.size.aspandas().groupby().agg("count")   
```
but a shorter way might be nice.

**Comment by leotrs** [comment]
My solution to this was proposed [here](https://github.com/ComplexGroupInteractions/xgi/issues/117#issuecomment-1198202029)

**Comment by maximelucas** [comment]
I think it would! As I mentioned in the related issue, just wondering about the call syntax with many dots.

**Comment by leotrs** [comment]
Closing this in favor of #117.
