### ISSUE TITLE
cleanup() not working for simplicial complexes

### ISSUE THREAD

**Issue by maximelucas** [xgi-org/xgi#195]
Because `cleanup()` uses HyperGraph specific methods and functions:
`XGIError: Cannot remove_edges_from to SimplicialComplex, use remove_simplices_from instead`

**Comment by leotrs** [comment]
@mcontisc that's odd. Can you please tell us what version you're using and whether you have installed xgi through pip or by cloning the repo?

**Comment by mcontisc** [comment]
my bad.. I was still using the old version 0.4.2. With the 0.4.3 it works. 
Sorry !!

**Comment by leotrs** [comment]
Glad we figured it out!

**Comment by mcontisc** [comment]
I am not sure if the issue should be closed though, because it was referring to simplicial complexes and my comment was for hypergraphs. Sorry for the confusion Leo!! I will remove my comments so that there is not misunderstanding. `cleanup` is still not working for simplicial complexes

**Comment by leotrs** [comment]
Woops you're right!

**Comment by nwlandry** [comment]
With the changes to the SimplicialComplex class (PR #247), multiedges are not allowed and I believe that singletons are required (although not sure how it's implemented right now). So I think that renumbering IDs and removing isolates is probably what should happen with a cleanup method.

**Comment by maximelucas** [comment]
Thanks for unearthing this. After PR #247, `cleanup()` does not raise an error anymore, but I feel its effect is not fully correct (or should be discussed). It can remove the following: 
- isolates (default): that works fine I think.
- multiedges (default): works fine but not needed as not allowed in SC class
- singletons (default): has an unwanted effect IMO. In the SC class, removing a simplex removes all other simplices that it is included in. So removing singletons removes all edges and triangles etc. that it is part of, even though the node corresponding to the singleton still exists. That's not really consistent, because when adding a 2-hyperedge {1,2,3}, the corresponding singletons are not added by `add_simplex`.

It also relabel by default which seems fine I agree.

**Comment by leotrs** [comment]
> singletons (default): has an unwanted effect IMO. In the SC class, removing a simplex removes all other simplices that it is included in. So removing singletons removes all edges and triangles etc. that it is part of, even though the node corresponding to the singleton still exists. That's not really consistent, because when adding a 2-hyperedge {1,2,3}, the corresponding singletons are not added by add_simplex.

Perhaps we should add a check to cleanup that just ignores the singletons flag and never touches them.
