### ISSUE TITLE
subhypergraph is poorly documented

### ISSUE THREAD

**Issue by leotrs** [xgi-org/xgi#237]
It is curently used in one tutorial but not terribly well covered.

This raises a more general issue of discoverability: how do we make sure that users are aware of all functionality at their disposal?

**Comment by maximelucas** [comment]
> This raises a more general issue of discoverability: how do we make sure that users are aware of all functionality at their disposal?

Great point. I think currently a lot of it is not (discoverable), e.g. the stats thing, but not only. 

I think having a logical subpackage structure is an important part of this. Right now, the `function.py` is in the subpackage `classes`. But I would not go to classes to look for most of what it contains. So we can probably improve on that aspect.

**Comment by leotrs** [comment]
Yeah function should not be inside classes.

Another idea is to have a place with examples/gallery/formulas/recipes that succinctly show what xgi is capable of.

**Comment by maximelucas** [comment]
I think this can be closed:
- subhypergraph is better documented
- function module has been reorganised #412 
- more tutos and cookbooks are on their way #414 #428 #429
