### ISSUE TITLE
Use tox?

### ISSUE THREAD

**Issue by arnaudon** [xgi-org/xgi#252]
Hello, I see you don't use https://tox.wiki/en/latest/, I'm happy to setup a PR to use it if you are interested. It is then very easy to run locally tests/linting/formating. 

For example, in the repo locally, one can do `tox -e format` to run black/isort, etc... or `tox -e lint` to check lint (or other formatting checks) pass, or `tox -e py` to run pytest, etc... 

Then tox can be called from github actions directly for CI.

**Comment by arnaudon** [comment]
As you prefer really. To me it simplifies things a lot, I tend to always have it in my repos, for the following reasons: 

- instead of all the optional items here: https://github.com/ComplexGroupInteractions/xgi/blob/main/CONTRIBUTING.md you'll have just the commands I wrote above.
- people won't need to learn how to use any of the formatting tools
- developers can add/modify them transparently to users (there are others nice tools like pycodestyle, pydocstyle, etc...)
- it's always in sync with CI
- the entire repo is formatted the same way (even with black, I have set lines of 100, but it seems here: https://github.com/ComplexGroupInteractions/xgi/pull/251/files it was formatted to 88)

There is also this nice tool: https://pre-commit.com/ which checks things locally before committing, to ensure commits are always good. I'm not using that one so often, as it prevents me to do 'dirty working' commits.

**Comment by nwlandry** [comment]
If I'm understanding correctly, we could potentially eliminate some of the suggested formatting steps in the CONTRIBUTING guide by doing all the formatting as a Github action? That could be cool if it's easy to implement.

**Comment by leotrs** [comment]
The trade-off is to install/configure tox, but yeah essentially I think what you're saying is correct.

**Comment by arnaudon** [comment]
I can make a PR to show you, it's fairly easy, I have several repos with it set it up already, it's just a matter of copy pasting a few files.

**Comment by nwlandry** [comment]
That would be cool to see how it works/what it does if you don't mind making a PR!

**Comment by arnaudon** [comment]
here is a first try: https://github.com/ComplexGroupInteractions/xgi/pull/281

**Comment by maximelucas** [comment]
Closing for now, see #281
