### ISSUE TITLE
testing long outputs from external file?

### ISSUE THREAD

**Issue by maximelucas** [xgi-org/xgi#259]
> I wonder if we're getting to the point where some of these longer test outputs should be read in from a file to declutter the tests, but I think that's a future discussion. Can you make it an open issue?

_Originally posted by @nwlandry in https://github.com/ComplexGroupInteractions/xgi/pull/257#discussion_r1053499570_

**Comment by leotrs** [comment]
In my experience, this is necessary/useful when either there is one HUGE data file or a multitude or little data files that all appear in similar tests.

I think the test referenced in #257 is long but okay to keep as it is currently.

I'm sure we'll get to the point where we need to use external data files for testing. Until then, I'm closing this.
