### ISSUE TITLE
Create a frozen hypergraph object

### ISSUE THREAD

**Issue by leotrs** [xgi-org/xgi#31]
We have discussed implementing a frozen object that would allow every statistic to be cached:
```python
H = some_hyper_graph()

H.adj_tensor()    # compute the tensor
# ...more code here...
H.adj_tensor()    # has to recompute

H.freeze()
H.adj_tensor()    # since H is frozen, it computes the tensor once and *caches it*
# ...more code here...
H.adj_tensor() # no need to recompute!
```

The point is that after `H` is frozen, we can essentially cache everything!
```python
H.freeze()
H.max_degree() # compute and cache
H.degree_histogram() # compute and cache
# etc
```

If at any point the user wants to modify `H` again, the cache is flushed,
```python
H.thaw() # everything that was cached is erased
H.add_edge([1,2,3])
H.max_degree() # need to recompute
H.freeze()
H.max_degree() # compute and cache
```

**Comment by iaciac** [comment]
Looks perfect ;)

**Comment by nwlandry** [comment]
Agreed ^^. I especially like the `thaw()` function.

**Comment by leotrs** [comment]
I think this is best left until after the basic interface has stabilized a bit. For example #20

**Comment by nwlandry** [comment]
Agreed.

**Comment by maximelucas** [comment]
We now have the [`freeze()`](https://xgi.readthedocs.io/en/latest/api/core/xgi.core.hypergraph.Hypergraph.html#xgi.core.hypergraph.Hypergraph.freeze) method so I think this can be closed?

It's "just" frozen and not caching anything though as far as I know.

**Comment by nwlandry** [comment]
Closed per team discussion today.
