### ISSUE TITLE
Unexpected absent return value in convert_to_hypergraph

### ISSUE THREAD

**Issue by leotrs** [xgi-org/xgi#327]
I'd expect `convert.convert_to_hypergraph` to ALWAYS return a hypergraph. However:

```python3
In [2]: xgi.convert_to_hypergraph([{1,2,3},{2,3},{3,4}])

In [3]: xgi.convert_to_hypergraph([{1,2,3},{2,3},{3,4}], create_using=xgi.Hypergraph)

In [4]: xgi.convert_to_hypergraph([{1,2,3},{2,3},{3,4}], create_using=xgi.Hypergraph())

In [5]: xgi.convert_to_hypergraph(None)
Out[5]: <xgi.classes.hypergraph.Hypergraph at 0x7faf87067190>
```

Only the last one has a return value! This is because `convert_to_hypergraph` is designed to be used alongside `create_using`, and populate the passed in hypergraph in-place. This is far from ideal, I'd say. We should redesign the interface of this and other functions in the `convert` module.

**Comment by maximelucas** [comment]
Not ideal indeed, good catch. 
+1 for making these convert functions more consistent.
