### ISSUE TITLE
Fix `See Also` links

### ISSUE THREAD

**Issue by nwlandry** [xgi-org/xgi#341]
Some of the functions listed in the `See Also` field in the docstrings aren't functioning links when they exist in another module. Perhaps a way to fix this: https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html

**Comment by nwlandry** [comment]
Checklist for docs (fix cross-references) before undrafting:

- [x] algorithms.assortativity
- [x] algorithms.centrality
- [x] algorithms.clustering
- [x] algorithms.connected
- [x] classes.function
- [x] classes.hypergraph
- [x] classes.hypergraphviews
- [x] classes.reportviews
- [x] classes.simplicialcomplex
- [ ] drawing.draw
- [ ] drawing.layout
- [ ] dynamics.synchronization
- [ ] generators.classic
- [ ] generators.lattice
- [ ] generators.random
- [ ] generators.simple
- [ ] generators.simplicial_complexes
- [ ] generators.uniform
- [ ] linalg.hodge_matrix
- [ ] linalg.hypergraph_matrix
- [ ] linalg.laplacian_matrix
- [ ] readwrite.bipartite
- [ ] readwrite.edgelist
- [ ] readwrite.incidence
- [ ] readwrite.json
- [ ] readwrite.xgi_data
- [ ] stats.edgestats
- [ ] stats.nodestats
- [ ] stats.__init__
- [ ] utils.utilities
- [ ] convert

**Comment by nwlandry** [comment]
I fixed some broken cross-reference links, fixed some small issues, and started making the optional arguments the format specified in the numpydoc specs.

I think that I will take a break from this because my soul feels a little dead after looking through lots of docstrings. There is a running checklist in Issue 343 to keep track of the global progress.

**Comment by maximelucas** [comment]
Partially solved with #343
