### ISSUE TITLE
Change to PyData sphinx theme

### ISSUE THREAD

**Issue by nwlandry** [xgi-org/xgi#351]
There was discussion that perhaps we could switch to the PyData Sphinx theme (https://pydata-sphinx-theme.readthedocs.io/en/stable/index.html).

**Comment by leotrs** [comment]
I think we should totally do it. The main thing tho is that the pydata theme has some extra stuff that other themes don't have, like cards, different admonition types, etc. So if we decide to go with it, and later down the road we want to change to another theme, it would be a non-trivial task.

Having said that, the pydata theme is adopted by the entire python scientific stack (that's its whole purpose) and it would visually tie us to the rest of the python ecosystem.

**Comment by nwlandry** [comment]
Good point - I'm in favor of this as well

**Comment by thomasrobiglio** [comment]
I guess this was completed with #576, right?

**Comment by maximelucas** [comment]
Yepp.

We can open other issues for further improvements.
