### ISSUE TITLE
New drawing style

### ISSUE THREAD

**Issue by nwlandry** [xgi-org/xgi#358]
It would be cool to have a method for drawing hypergraphs/simplicial complexes in the style of Fig. 1 in [this paper](https://arxiv.org/abs/2104.05457).

**Comment by maximelucas** [comment]
Agreed. 

The first step would be to have an `order` param in `draw` to only draw a given order?
Like I did in Fig 1c here https://journals.aps.org/prresearch/pdf/10.1103/PhysRevResearch.2.033410
At that (pre-XGI time), I did it this way with the function `plot_simplicial_pure()` available here 
https://github.com/maximelucas/plot_simplicial_complex/blob/main/draw_simplicial_complexes.ipynb

Then we can choose to have it look like a multilayer or not I guess.

**Comment by thomasrobiglio** [comment]
That would be nice! @nwlandry this could be done using matplotlib 3D plotting right? Or you had something else in mind?

**Comment by nwlandry** [comment]
Awesome! That's a great starting point.

Yeah, I was picturing using 3d plotting and Max's code as well as [this script](https://github.com/jkbren/matplotlib-multilayer-network) for plotting multilayer networks is a good place to start, I think.

**Comment by thomasrobiglio** [comment]
If nobody is already working on it I might try to build it.

**Comment by nwlandry** [comment]
Sounds great!!
