### ISSUE TITLE
Add a shortest path algorithm

### ISSUE THREAD

**Issue by acombretrenouard** [xgi-org/xgi#365]
We could add an algorithm that computes shortest paths between nodes.
The notion of path is not unique, but a starting point could be : "_An ordered list of nodes where two consecutive nodes belong to at least one hyperedge. All nodes are distincts._"

I wrote such a feature, based on method [`all_shortest_paths`](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.shortest_paths.generic.all_shortest_paths.html#all-shortest-paths) from `networkx`.

I can work on adding it to the basecode !

**Comment by nwlandry** [comment]
Great idea, Antoine - this would be awesome to add to XGI!

**Comment by nwlandry** [comment]
Fixed by #368.
