### ISSUE TITLE
Add a Katz-centrality measure

### ISSUE THREAD

**Issue by acombretrenouard** [xgi-org/xgi#366]
Given a model for random walkers on hypergraphs, one can define the **Kayz-centrality** of a node as the average fraction of walkers sitting on this node at equilibirum.

The simplest random walker we could think of could :
1. select an hyperedge at random among those containing the current node,
2. jump to a random node of this hyperedge (remaining on the current node is not allowed).

I have written a code for this feature and I would be happy to contribute.

**Comment by lordgrilo** [comment]
Hello!

Yes, good idea! The natural place to add it would be centrality.py in the algorithms folder. 
Please go ahead with a pull request.
