### ISSUE TITLE
Complement of a hypergraph

### ISSUE THREAD

**Issue by acombretrenouard** [xgi-org/xgi#367]
We could define the complement of a hypergraph H :
1. we take the same set of nodes, there are N of them,
2. for each hyperedge size i up to the size I_max of the biggest hyperedge in H, we add to our new graph all possible hyperedges **but** the ones that are allready in H. These are "N choose i" possible hyperedges of size i.

This operation is computationally cumbersome but is rather general.
I also have wrote a version of it.

**Comment by maximelucas** [comment]
That's interesting, do you have a practical case where you use this?
In any case yes, happy have a PR on this!
I'm thinking one efficient way to implement it could be `H_complement = H_complete - H` where `H_complete = xgi.complete_hypergraph(N)`. I think we have implemented the "-" operation between hypergraphs.

**Comment by nwlandry** [comment]
Yeah, that's an interesting idea! Maybe add a warning when the computation time will be particularly burdensome? (Some function of max size and number of nodes)?

**Comment by leotrs** [comment]
An example or reference/citation would be helpful here :)

**Comment by acombretrenouard** [comment]
Quick question : where should I put a `complement_hypergraph` function ?
Maybe in `/Users/antoine/Documents/X/4A/ICFP/Stage_CPT/code/xgi/xgi/classes/function.py` ?

**Comment by leotrs** [comment]
Yeah I'd say that's the right place for now.
