### ISSUE TITLE
viz: node_fc_cmap does not work if node_fc is not a NodeStat

### ISSUE THREAD

**Issue by maximelucas** [xgi-org/xgi#389]
Let's say we plot a simple hypergraph

```python
edges = [[1, 2], [1, 2, 3], [2, 3], [3, 4, 5, 6]]
H = xgi.Hypergraph(edges)

# plot node size ~ degree, with shades of green
xgi.draw(H, node_fc=H.nodes.degree, node_fc_cmap=mpl.colormaps["Greens"])
```

Here `H.nodes.degree` is a `NodeStat`, it works:
![Screenshot 2023-06-07 at 12 01 21](https://github.com/xgi-org/xgi/assets/7493360/9980ec10-1134-4dfe-a444-e60788afa249)

But if we replace it by a list with the same values  `H.nodes.degree.aslist()`, the cmap is discarded and back to its default:
![Screenshot 2023-06-07 at 12 04 05](https://github.com/xgi-org/xgi/assets/7493360/2c808c16-9122-466e-94aa-4cde38080b33)

I guess we may have a similar problem with related variables:  `node_ec_cmap`, `dyad_color_cmap`,  `edge_fc_cmap`.

**Comment by nwlandry** [comment]
PR #402 fixes this, but I need to figure out why it breaks the unit tests for drawing...

**Comment by nwlandry** [comment]
Any ideas, @thomasrobiglio or @maximelucas?

**Comment by thomasrobiglio** [comment]
see https://github.com/xgi-org/xgi/pull/402#issuecomment-1591699876
