### ISSUE TITLE
Issue with draw_dihypergraph

### ISSUE THREAD

**Issue by nwlandry** [xgi-org/xgi#393]
Screenshot of the error:
<img width="814" alt="Screenshot 2023-06-08 at 8 46 18 PM" src="https://github.com/xgi-org/xgi/assets/8760347/29f7ccc4-401e-40ba-9241-ea681b81e90f">

**Comment by leotrs** [comment]
@thomasrobiglio would you like to take a stab here? The main problem is that L1636 is assuming that nodes' IDs are integers :)

**Comment by thomasrobiglio** [comment]
Yes, working on it now!
