### ISSUE TITLE
xgi.Hypergraph(SC) not working anymore?

### ISSUE THREAD

**Issue by maximelucas** [xgi-org/xgi#398]
Running 

```python
S = xgi.random_simplicial_complex(10, [0.05, 0.01], seed=1) # non-empty SC
H = xgi.Hypergraph(S) # convert SC to HG
```

yields an empty Hypergraph: no nodes and no edges. 

I'm pretty sure this used to work?

**Comment by thomasrobiglio** [comment]
I think I've found the bug (coming from one of my first PR, the one about the convert function), I will open the PR
