### ISSUE TITLE
"projects using xgi" link not working 

### ISSUE THREAD

**Issue by maximelucas** [xgi-org/xgi#418]
https://github.com/xgi-org/xgi

I get an error 404 when I click on the link. 
I think it's because it's linking to the "stable" version of the docs, but the page only exists on the "latest" version of it.

**Comment by nwlandry** [comment]
This will be fixed when I put a new release on PyPI. It is a bit annoying that the docs on stable that are unrelated to the API can't get updated immediately. Let me look more into it.

**Comment by nwlandry** [comment]
Fixed.
