### ISSUE TITLE
Cookbook - list suggestion

### ISSUE THREAD

**Issue by maximelucas** [xgi-org/xgi#428]
As discussed, we want to have a cookbook.

Examples from other libraries:
- [scipy](https://scipy-cookbook.readthedocs.io/items/Recarray.html)
- [itertools](https://docs.python.org/3/library/itertools.html#itertools-recipes)
- [pandas](https://pandas.pydata.org/docs/user_guide/cookbook.html)

What do we want in the cookbook? Here's a unorganised list of suggestions (let's keep updating it):
- create a random hypergraph
- plot histogram of degrees
- plot histogram of edge sizes
- create subhypergraph based on node list
- create subhypergraph by keep edges of order d
- cleanup
- merge duplicate edges
- add two hypergraphs
- filterby 
- plot hypergraph showing one order only
- plot with stats

What do we want the cookbook to be like? 
My first thought would be a list of short tricks, like a few lines of things we often do but may not have a dedicated function in XGI. Or showcase a short example of one commonly-used option in a function. More or less like itertools? Pandas' one looks more like a full-flegded tutorial. I would maybe expand each of the short tricks in the cookbook in longer tutorials/pages if needed. Very open to other ideas, we should discuss this.

**Comment by nwlandry** [comment]
Some other potential recipes:

* Print out the major statistics of the hypergraph that one might want to report in a data table: number of nodes and edges, mean degree, mean edge size.
* Merge multiedges and show a scatter plot of edge size vs. multiplicity with the marginals plotted on the x and y axes. 
* Show use of NetworkX and XGI together? Maybe other libraries as well?
* A more specific example of plotting with stats could be to import the congress-bills dataset and plot the degree distributions etc. for the major political parties, and color a network vis with the party affiliations (although that might be very computationally expensive)
* Maybe snippets from this project? https://github.com/nwlandry/filtering-higher-order-datasets

**Comment by nwlandry** [comment]
Subhypergraph methods are lower priority.

* start from a pairwise network and convert to hypergraph
