### ISSUE TITLE
User guides - suggestions for explanation pages

### ISSUE THREAD

**Issue by maximelucas** [xgi-org/xgi#429]
Some of the features would benefit for a more in-depth explanation than just the API: explanations, example, use cases, etc.

I'm thinking of something along the lines of this [pandas page](https://pandas.pydata.org/docs/user_guide/reshaping.html#reshaping) about reshaping dataframes. 

The first ones that come to mind: 
- stats
- drawing

Other ideas? 
Also it would be nice to have it nicely integrated in the online docs, not just as a notebook, but not sure what the best way to do this is.

**Comment by leotrs** [comment]
How is this separate from tutorials? Where in the following chart would you
place what you're suggesting? https://diataxis.fr/

**Comment by maximelucas** [comment]
Good question. In my mind it could be Explanation (bottom left). 

For example, I see this [page](https://pandas.pydata.org/docs/user_guide/reshaping.html#reshaping) as something that explains some functionalities of the Reference. The Reference tells you what it does, the arguments, etc. Here I would explain some of these with more words, examples, etc. 

We might need to clarify if there's an overlap with some of the tutos we suggested. If so, either we manage to conceptually clarify what goes where and could have, say for stats, both a tuto and a user-guide. If not, we could have one of the two.

What do you think?

**Comment by leotrs** [comment]
Yeah with this diataxis framework there is going to be some overlap. As long as the purpose of each document is clear, that's fine.

**Comment by thomasrobiglio** [comment]
Hi! This has been open for some time... do you think this is still relevant?---we did some work with the recipes and the new tutorials but I think we are still somewhat missing a part of the **explanation** quadrant of the diataxis.

In case I can try to do a tentative one about `stats` or `drawing`, we can then see how we like it. This should be easily doable using a notebook with a lot a markdown text.

**Comment by leotrs** [comment]
Happy to close

**Comment by nwlandry** [comment]
Agreed. Let's close. We have implemented most of this already.
