### ISSUE TITLE
remove paper branch

### ISSUE THREAD

**Issue by nwlandry** [xgi-org/xgi#431]
I would suggest we remove the `paper` branch from this repo and put the contents of the joss paper in a separate repo. Thoughts on this?

**Comment by maximelucas** [comment]
It's basically 4 files. I'm not sure I would create a new repo just for that. 
What's your reasoning behind not liking the current branch?

**Comment by nwlandry** [comment]
Discussed with Max and Alice and they were okay with doing this.
