### ISSUE TITLE
`sep` argument not working multilayer plotting function

### ISSUE THREAD

**Issue by maximelucas** [xgi-org/xgi#433]
It seems to have no effect

**Comment by thomasrobiglio** [comment]
uhm I will have a look at it! thank you @maximelucas

**Comment by nwlandry** [comment]
Hi @thomasrobiglio - I started adding some features to `draw_multilayer` - can I push this first?

**Comment by maximelucas** [comment]
Okay nice :) This is with the new version?
Then maybe just document this yes. Could even be nice to give a rough idea/example of when it starts not having an effect.

**Comment by thomasrobiglio** [comment]
>> This is with the new version?

Yes, but it should work the same in the stable version

>> Could even be nice to give a rough idea/example of when it starts not having an effect.

Good idea, let's keep the issue open and I will work on this
