### ISSUE TITLE
Strange drawing behavior for large edges

### ISSUE THREAD

**Issue by nwlandry** [xgi-org/xgi#466]
For
```python
import xgi
H = xgi.sunflower(3, 1, 50)
xgi.draw(H, node_size=5)
```
the plot looks like
![image](https://github.com/xgi-org/xgi/assets/8760347/ec6b4f1b-6061-4cba-8991-842fb680dbf2)

**Comment by maximelucas** [comment]
What specifically do you think should be different?

I guess this hypergraph has 3 edges of size 50, so each hyperedge should almost look like a regular polygon, or at least some convex shape. And the we could ideally want the center node to be closer to the "flowers"?

I tried playing with the spring strength `k` of the layout and managed to get this:

```python
import xgi
H = xgi.sunflower(3, 1, 50)

pos = xgi.barycenter_spring_layout(H, k=0.25)
xgi.draw(H, node_size=5, pos=pos)
```
<img width="336" alt="Screenshot 2023-09-01 at 17 08 24" src="https://github.com/xgi-org/xgi/assets/7493360/376828c8-7955-4fc5-b024-d60a71bc3e25">

**Comment by nwlandry** [comment]
It seems weird to me that despite very few constraints that the edge isn't convex.

**Comment by maximelucas** [comment]
@nwlandry I think you investigated this but I don't remember the conclusion. Should this be closed?

**Comment by nwlandry** [comment]
Thanks for the reminder, @maximelucas! You're right. The issue is that the edges are not necessarily convex, but this was addressed with the `draw_hypergraph_hull()` function introduced in PR #320 authored by @thomasrobiglio.
