### ISSUE TITLE
links in tutorials are not working

### ISSUE THREAD

**Issue by thomasrobiglio** [xgi-org/xgi#485]
This was expected as I had written by hand the links. I will list them here and open a PR soon.

- [x] 5 mins -> focus tutorial on plotting
- [x] stats package paga -> focus tutorial on stats
- [x] xgi.stats.MultiDiEdgeStat -> focus tutorial on stats
- [x] ... all the classes in the stats package point to the tutorial, there should be 8 of them in total
- [x] ... all the modules  in the stats package point to the tutorial on stats, there should be 4 of them
- [x] stats landing [page](https://xgi.readthedocs.io/en/stable/api/stats.html) -> focus tutorial on stats
- [x] ... views same as stats (see above)
- [x] Hypergraph class -> focus tutorial on statistics
- [x] DiHypergraph class -> focus tutorial on statistics

let me know if you happen to find others

**Comment by nwlandry** [comment]
I'm pretty sure that I addressed most of the link issues with #487, but it would be good to double-check what I did.

**Comment by thomasrobiglio** [comment]
Thank you very much @nwlandry, I have checked: all the non-functioning links that are listed are now ok. closing this.
