### ISSUE TITLE
how to calculate the average path length?

### ISSUE THREAD

**Issue by YuhuYang** [xgi-org/xgi#511]
how to calculate global indicators of hypergraphs? Like the average path length, diameter

**Comment by maximelucas** [comment]
Thanks for the question @YuhuYang.

For a hypergraph `H`, you can compute all shortest path lenghts with `spl = xgi.shortest_path_length(H)`.
Note: this gives and infinite length for disconnected nodes.

You can then just collect the lengths and take the average like so:

```python
lens = []
for tup in spl:
    lens += tup[1].values()

# remove lengths 0 for self-loops
lens = [i for i in lens if i!=0] 

# replace inf by 0 for disconnected nodes
lens = [0 if i==np.inf else i for i in lens] 

avg_shortest_path = np.sum(lens) / (N * (N-1)) # = np.mean(lens)
```

You can find other global measures by exploring [this page](https://xgi.readthedocs.io/en/stable/api/algorithms.html). You can find assortativity measures, clustering coefficient, or the [density](https://xgi.readthedocs.io/en/stable/api/algorithms/xgi.algorithms.properties.html#xgi.algorithms.properties.density) for example.

**Comment by YuhuYang** [comment]
> Thanks for the question @YuhuYang.
> 
> For a hypergraph `H`, you can compute all shortest path lenghts with `spl = xgi.shortest_path_length(H)`. Note: this gives and infinite length for disconnected nodes.
> 
> You can then just collect the lengths and take the average like so:
> 
> ```python
> lens = []
> for tup in spl:
>     lens += tup[1].values()
> 
> # remove lengths 0 for self-loops
> lens = [i for i in lens if i!=0] 
> 
> # replace inf by 0 for disconnected nodes
> lens = [0 if i==np.inf else i for i in lens] 
> 
> avg_shortest_path = np.sum(lens) / (N * (N-1)) # = np.mean(lens)
> ```
> 
> You can find other global measures by exploring [this page](https://xgi.readthedocs.io/en/stable/api/algorithms.html). You can find assortativity measures, clustering coefficient, or the [density](https://xgi.readthedocs.io/en/stable/api/algorithms/xgi.algorithms.properties.html#xgi.algorithms.properties.density) for example.

Thank you very much!

**Comment by maximelucas** [comment]
Note for self: not closing because we could put this a recipe or new function.

**Comment by YuhuYang** [comment]
However, the code costs much time (now, about 30 minutes). The num of nodes is around 6000. Is this situation normal? (I have used the largest connected component) 
![image](https://github.com/xgi-org/xgi/assets/140584393/ae5ff63d-8f5e-4c9b-95b8-ee8519e1c811)

**Comment by maximelucas** [comment]
Can you check what part is taking time? I expect it is the `shortest_path_length()` function. Computing shortest paths is expensive in general.

**Comment by YuhuYang** [comment]
Yes, its is the `shortest_path_length()`. Are there some methods can decrease the time cost?

**Comment by thomasrobiglio** [comment]
Hi @YuhuYang! Computing the shortest past between two nodes is a computationally complex task, so it's normal for it to take some time.
In XGI I think we have implemented a version of [Dijkstra's algorithm](https://en.wikipedia.org/wiki/Dijkstra%27s_algorithm) which has a computational complexity of O(N^2) --N here is the number of nodes-- for a single node. 
`shortest_path_length()` does this for every node in your structure so you will have something O(N^3) which is quite slow.
In addition to this polynomial cost of the procedure, XGI is implemented in python which is notably slower than other programming languages.

My suggestions to  decrease the computational cost are:
1. Parallelize the operation by calling `single_source_shortest_path_length()` for every node in your structure but using different cores of your machine. You can do this using for example the [multiprocessing](https://docs.python.org/3/library/multiprocessing.html) package.
2. Use libraries for networks which are implemented in C++ or other faster languages and then wrapped in python, notable examples are `graph_tool` (see [here](https://graph-tool.skewed.de/static/doc/autosummary/graph_tool.topology.shortest_path.html#graph_tool.topology.shortest_path) for the corresponding function) or `reticula` ([here](https://docs.reticula.network/algorithms/static_network_reachability.html#_CPPv4I_11static_edgeE26shortest_path_lengths_fromNSt13unordered_mapIN5EdgeT10VertexTypeENSt6size_tE4hashIN5EdgeT10VertexTypeEEEERK7networkI5EdgeTERKN5EdgeT10VertexTypeE)).

I hope this helps! Happy coding!

**Comment by YuhuYang** [comment]
Thanks again! I'll try them!

**Comment by thomasrobiglio** [comment]
> 2\. Use libraries for networks which are implemented in C++ or other faster languages and then wrapped in python, notable examples are `graph_tool` (see [here](https://graph-tool.skewed.de/static/doc/autosummary/graph_tool.topology.shortest_path.html#graph_tool.topology.shortest_path) for the corresponding function) or `reticula` ([here](https://docs.reticula.network/algorithms/static_network_reachability.html#_CPPv4I_11static_edgeE26shortest_path_lengths_fromNSt13unordered_mapIN5EdgeT10VertexTypeENSt6size_tE4hashIN5EdgeT10VertexTypeEEEERK7networkI5EdgeTERKN5EdgeT10VertexTypeE)).

`graph_tool` is not a library for higher-order structures (I am less familiar with `reticula`), so you would need to take the skeleton of you hypergraph/simplicial complex and compute the paths on the corresponding graph.
