### ISSUE TITLE
Add a way to specify `vmin` and `vmax`

### ISSUE THREAD

**Issue by nwlandry** [xgi-org/xgi#536]
When trying to plot a color bar for nodal values, (the same is true for edge/dyad colors as well) it would be great to be able to add the ability to specify vmin and vmax as is done in matplotlib [scatter](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.scatter.html).

**Comment by maximelucas** [comment]
Is this not already the case? In `draw()` `draw_nodes()` `draw_hyperedges()` etc.

**Comment by nwlandry** [comment]
😅 good call. That was an oops on my part! Closing this now.
