### ISSUE TITLE
add back edgecolor argument to draw hulls with white face but colored contour

### ISSUE THREAD

**Issue by maximelucas** [xgi-org/xgi#537]
To get something like this:

<img src="https://github.com/xgi-org/xgi/assets/7493360/cc4d909f-edcf-4659-ac3a-672417320d9d" width="35%">

**Comment by nwlandry** [comment]
Can you comment on what you would like the call to be to draw the above figure? Like a minimal working example.

**Comment by maximelucas** [comment]
I started a branch a few days ago, I'll push soon!

**Comment by nwlandry** [comment]
Great! Looking forward to it!
