### ISSUE TITLE
cannot easily find the functions for loading the datasets in the docs?

### ISSUE THREAD

**Issue by maximelucas** [xgi-org/xgi#548]

**Comment by nwlandry** [comment]
From #540:
"`xgi.load_xgi_data("<dataset_name>")` is not documented anywhere (except from its own docstring).
As far as I can tell it only appears here, but without all its arguments: https://xgi.readthedocs.io/en/stable/xgi-data.html."

**Comment by nwlandry** [comment]
@maximelucas --- what do you picture needing to be done in order to close this? Happy to fix this so long as there is a concrete plan.

**Comment by maximelucas** [comment]
It's in the [Reference](https://xgi.readthedocs.io/en/stable/api/readwrite/xgi.readwrite.xgi_data.html), and there's also a link from[ XGI-data](https://xgi.readthedocs.io/en/stable/xgi-data.html) to the Reference, so I think it should be fine now.
