### ISSUE TITLE
strange datatype of unique_edge_size()

### ISSUE THREAD

**Issue by maximelucas** [xgi-org/xgi#566]
Running 
```python
H = xgi.load_xgi_data("email-enron")
xgi.unique_edge_sizes(H)
```

yields 

```python
[np.int64(1),
 np.int64(2),
 np.int64(3),
...
 np.int64(36),
 np.int64(37)]
```

I don't remember these elements being `np.int64`. There's probably nothing wrong with it but it looks unnecessary.
This might be due to the new numpy version 2.0?

**Comment by nwlandry** [comment]
Yes, that's correct! If you want to make a quick PR casting the values to int and adding a short test confirming the data type, I'll approve it!
