### ISSUE TITLE
Add a `unique` method to stats

### ISSUE THREAD

**Issue by nwlandry** [xgi-org/xgi#602]
It would be nice to be able to call
```python
import xgi
H = xgi.load_xgi_data("email-enron")
H.edges.size.unique()
```

**Comment by apurvabanka** [comment]
@nwlandry I would like to give this a try. Can you assign me this issue?

**Comment by nwlandry** [comment]
@apurvabanka --- I saw that you had posted a comment saying that you would like to address this. PR #603 addresses this, but can you take a look at the PR and see if that was what you were picturing? I would really appreciate it!
