### ISSUE TITLE
Error in local_clustering_coefficient function

### ISSUE THREAD

**Issue by cosimoagostinelli** [xgi-org/xgi#607]
https://github.com/xgi-org/xgi/blob/139a2bc5f1cff7f77090d1e7b882821833b7fe0b/xgi/algorithms/clustering.py#L137C1-L140C2

I think that the two 'for' cycles are not correct because 'range(dv)' does not identify the hyper-edges to which the node n belongs.
Since we have to go over all the possible pairs of hyperedges (without repetition) containing the node n, I guess that one possible correct implementation may be (instead of lines 137-140): 

            for e1, e2 in combinations(ev, 2):
                
                edge1 = members[e1]
                edge2 = members[e2]

To test this issue one can build a pairwise hypergraph H from a networkx graph G and check if the local_clustrering_coefficient of H matches the classic clustering coefficient of G as it should (by definition of local clustering coefficient). 

          G = nx.[any_network] ([params])
          edges = G.edges
          nodes = G.nodes
          H = xgi.Hypergraph()
          H.add_nodes_from(nodes)
          H.add_edges_from(edges)
          
          lcc = xgi.local_clustering_coefficient(H)
          cc = nx.clustering_coefficient(G)
          
          cc =? lcc 

I tried and the two results do not correspond when using the  local_clustrering_coefficient function, while they do if I modify the for loop as above.

Thank you for your consideration!

**Comment by maximelucas** [comment]
Thanks Cosimo we'll have a look! Would you be up to write a Pull Request with the changes you're suggesting?

**Comment by cosimoagostinelli** [comment]
Sure! sorry, I forgot.
