### ISSUE TITLE
Documentation missing for `watts_strogatz_hypergraph`

### ISSUE THREAD

**Issue by tlarock** [xgi-org/xgi#615]
I was looking at the `generators` module and noticed that there is no documentation for [`watts_strogatz_hypergraph`](https://github.com/xgi-org/xgi/blob/98a46e9d128a4eeff3f370d2bc3d37d3d9b370d9/xgi/generators/random.py#L436). While reading the source is enough to broadly understand the generation process, I am not familiar with the origins of this model, so it would be helpful to add a description and reference. It may also be useful to give the parameters more meaningful names (or just explain that they are inputs to `ring_lattice`, plus a rewire probability).

**Comment by nwlandry** [comment]
I believe that @leotrs wrote this function. Leo, do you have a reference for this?
