### ISSUE TITLE
Issue with `node_edge_centrality`

### ISSUE THREAD

**Issue by nwlandry** [xgi-org/xgi#616]
I have been trying to get the `node_edge_centrality` to work, but for this minimal working example,
```python
import xgi
H = xgi.load_xgi_data("email-enron")
H.cleanup()
c5 = H.nodes.node_edge_centrality.asnumpy()
```
it raises the error
```zsh
RuntimeWarning: invalid value encountered in divide
  new_x = np.sign(u[0].item()) * u
RuntimeWarning: invalid value encountered in divide
  new_y = np.sign(v[0].item()) * v
UserWarning: Iteration did not converge!
  warn("Iteration did not converge!")
```
This shouldn't happen because the graph is connected, but maybe I'm missing something.

**Comment by maximelucas** [comment]
Not providing a solution but just confirming I get the same. 
It's a warning though and not an error, so there is an output but it's an array full os NaNs.
