### ISSUE TITLE
Add performance benchmarks

### ISSUE THREAD

**Issue by nwlandry** [xgi-org/xgi#629]
Using asv to benchmark XGI has proved infeasible. Some possible alternatives:
* [github-action-benchmark](https://github.com/benchmark-action/github-action-benchmark) with [pytest-benchmark](https://github.com/ionelmc/pytest-benchmark)
* [pyperf](https://pyperf.readthedocs.io/en/latest/).

I think the first of these seems most doable.

**Comment by nwlandry** [comment]
PR #630 fixed this partially, but needs tweaking to more effectively present to end users.

**Comment by nwlandry** [comment]
Closing this issue as completed and opening a new issue with a checklist for items to still be done.

**Comment by maximelucas** [comment]
> Using asv to benchmark XGI has proved infeasible.

Do you remember why that was? For the record.

**Comment by nwlandry** [comment]
> > Using asv to benchmark XGI has proved infeasible.
> 
> Do you remember why that was? For the record.

(1) I never managed to get a GitHub Action working for asv and (2) I couldn't run it locally, because I kept getting errors related to sympy. Note that the [`benchmark-action](https://github.com/benchmark-action/github-action-benchmark?tab=readme-ov-file#future-work) action has plans to support this in the future, so I see this as a good first step.
