### ISSUE TITLE
Which should be the default? Edge ids or edge members?

### ISSUE THREAD

**Issue by leotrs** [xgi-org/xgi#79]
I'm just wondering if we still wanted to implement this solution https://github.com/ComplexGroupInteractions/xgi/issues/28#issuecomment-997406815 that we seemed to agree on. But then we didn't implement it.

Namely, something more like

```python
H = xgi.Hypergraph([[1, 2, 3], [3, 4], [4, 5, 6]])

H.edge_ids
# -> EdgeIDView((0, 1, 2))
H.edges
# -> EdgeView([[1, 2, 3], [3, 4], [4, 5, 6]])
H.edges(return_dict=True)
# -> {0: [1, 2, 3], 1: [3, 4], 2: [4, 5, 6]}
```
I think the reasoning was that it makes it shorter and more straightforward to see the members, as well as being consistent with networkx's edges. 

_Originally posted by @maximelucas in https://github.com/ComplexGroupInteractions/xgi/issues/70#issuecomment-1080708993_

**Comment by nwlandry** [comment]
I think that this can be closed?

**Comment by leotrs** [comment]
Coming back to this months later, I haven't changed my mind: I don't think implementing this is necessary. But @maximelucas might disagree :)
